stages:
  - build
  - test
  - push-image
  - deploy-project

variables:
  DOCKER_DRIVER: overlay2
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: env_analysis
  MONGO_INITDB_DATABASE: admin
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: admin

build:
  stage: build
  image: ${REGISTRY_UTILS_PATH}debian9-custom:1.0.3
  script:
    - sh ./scripts/pipeline/build-project.sh
  tags:
    - brhsa-runner

linter:
  stage: test
  image: ${REGISTRY_UTILS_PATH}debian9-custom:1.0.3
  script:
    - sh ./scripts/pipeline/build-project.sh
    - sh ./scripts/pipeline/run-linter.sh
  tags:
    - brhsa-runner
test:
  stage: test
  image: ${REGISTRY_UTILS_PATH}debian9-custom:1.0.3
  services:
    - name: ${REGISTRY_UTILS_PATH}mongo:4.4.1
      alias: mongo
    - name: ${REGISTRY_UTILS_PATH}postgres:13
      alias: postgres
  script:
    - sh ./scripts/pipeline/build-project.sh
    - sh ./scripts/pipeline/run-tests.sh
  tags:
    - brhsa-runner

push-image:
  stage: push-image
  image: ${REGISTRY_UTILS_PATH}docker:dind
  before_script:
    - echo "Logging in to registry"
    - docker login $NEXUS_HOST:$NEXUS_PORT -u $NEXUS_USER -p $NEXUS_PASS
  script:
    - sh ./scripts/pipeline/push-image.sh
  after_script:
    - docker logout $NEXUS_HOST:$NEXUS_PORT
  tags:
    - brhsa-runner
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $BRANCH_DEV
      - $CI_COMMIT_REF_NAME == $BRANCH_HML
      - $CI_COMMIT_REF_NAME == $BRANCH_PRD
      - $CI_COMMIT_TAG != null

deploy-project:
  stage: deploy-project
  image: ${REGISTRY_UTILS_PATH}docker:dind
  before_script:
    - echo "Logging in to registry"
    - docker login $NEXUS_HOST:$NEXUS_PORT -u $NEXUS_USER -p $NEXUS_PASS
  script:
    - sh ./scripts/pipeline/deploy-project.sh
  after_script:
    - docker logout $NEXUS_HOST:$NEXUS_PORT
  tags:
    - brhsa-runner
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $BRANCH_DEV
      - $CI_COMMIT_REF_NAME == $BRANCH_HML
      - $CI_COMMIT_REF_NAME == $BRANCH_PRD
