version: "3.8"
services:
  mongo:
    image: mongo:4.4.1
    volumes:
      - ./node_modules/pill-helper-sdk/scripts/database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
